const bit<16> TYPE_IPV4 = 0x800;
const bit<5>  TYPE_FLOWINFO = 31;

const bit<4>  TYPE_EGRESS_HOST = 1;
const bit<4>  TYPE_EGRESS_SWITCH = 2;

#define PKT_INSTANCE_TYPE_NORMAL 0
#define PKT_INSTANCE_TYPE_INGRESS_CLONE 1
#define PKT_INSTANCE_TYPE_EGRESS_CLONE 2
#define PKT_INSTANCE_TYPE_COALESCED 3
#define PKT_INSTANCE_TYPE_INGRESS_RECIRC 4
#define PKT_INSTANCE_TYPE_REPLICATION 5
#define PKT_INSTANCE_TYPE_RESUBMIT 6

#define THRESHOLD 25
#define PORT_NUM 8